//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FRES.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FRESDBEntities : DbContext
    {
        public FRESDBEntities()
            : base("name=FRESDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Address> Address { get; set; }
        public virtual DbSet<Location> Location { get; set; }
        public virtual DbSet<RealEstateE> RealEstateE { get; set; }
        public virtual DbSet<RealEstateT> RealEstateT { get; set; }
        public virtual DbSet<RealEstateType> RealEstateType { get; set; }
        public virtual DbSet<Address_bak> Address_bak { get; set; }
    }
}
